name: Release

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          path: bb-component-SuperTable

      - uses: actions/checkout@v3
        with:
          repository: nutgood/bb-component-SuperTableColumn
          ref: main
          path: bb-component-SuperTableColumn

      - uses: actions/checkout@v3
        with:
          repository: poirazis/bb-component-SuperTableCell
          ref: main
          path: bb-component-SuperTableCell

      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Make the production plugin bundle
        run: |
          cd bb-component-SuperTable
          release_version=$(cat package.json | jq -r '.version')
          echo "RELEASE_VERSION=$release_version" >> $GITHUB_ENV
          yarn
          yarn build
      - name: Perform Github Release
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ env.RELEASE_VERSION }}
          tag_name: v${{ env.RELEASE_VERSION }}
          generate_release_notes: true
          files: |
            dist/*.tar.gz
